### ISSUE TITLE
Research software development stack or framework to use

### ISSUE THREAD

**Issue by fanbondi** [Land-Registry-GM/landregistry.gm#3]
We should quickly decide which framework and or software stack to use to build this system. We must take our time to decide which one is the best by considering what the team is conversant in and which will lead to a great PoC/MVC. Also, we should consider how we can extend it to be compatible with blockchain.  In this space let us discuss and finalise. 

### Possible tech stack

| Stack       | Frontend    | Backend     | Database               | Best For                          |
|-------------|-------------|-------------|------------------------|-----------------------------------|
| Django  | Vue.js/React| Django      | PostgreSQL + PostGIS   | GIS mapping, compliance, security |
| MERN    | React       | Node.js     | MongoDB/PostgreSQL     | Real-time updates, JSON APIs      |
| Laravel | Livewire    | Laravel     | MySQL/PostgreSQL       | Low-cost hosting, rapid MVP       |
| .NET + Vue.js    | Vue.js    | ASP.NET Core    | SQL Server/PostgreSQL | Enterprise-grade apps, scalability, strong security, blockchain extensibilittyping with C#

**Comment by ChernoAlieu** [comment]
Dotnet???

**Comment by fanbondi** [comment]
> Dotnet???

Sure, add more information about Dotnet. Extend the table accordingly.

**Comment by ChernoAlieu** [comment]
> > Dotnet???
> 
> Sure, add more information about Dotnet. Extend the table accordingly.

Done... Added it

**Comment by alagiesellu** [comment]
I vote for **MERN**

JavaScript has a diverse and flexible ecosystem. I also believe more developers has at least some experience with JS ecosystem.

From my experience working with blockchain technology, JavaScript has more well developed libraries for interacting with blockchain networks Ethers.js and Web3.js.

When we also start working on Mapping features, JS would be more advantagous.

Parallel execution in JavaScript is plus especially for project with long term vision.

All the above points I mentioned, maybe other frameworks might do one, two or all better than JS. From my experience, I favor JS for such project.

**Comment by fanbondi** [comment]
I think most of these options are great; we have to see what our team is conversant with. So far, it is just the three of us that have commented, so let's give it a day or two to finalise.

**Comment by Massay** [comment]
Great options.
I believe  any stack the team chose should be fine.
We will just learn in the process

**Comment by alagiesellu** [comment]
Let's get everyone's vote in. 

I choosed MERN, relatively new to it, still have some learning curve to do on it. 

But I am most confortable and able with Laravel stack.

It would still be better to get everyone share what they vote for. 

And on a second thought, since especially this is a new team, and we would have to manage diverse team work challanges, Laravel is much easier to manage based on my experience compared to JS. Package management and maintenance can be a mess, especially when we don't have a JS expert with, I won't reccomend this route. 

Let's also hear everyone 1st and 2nd choise. 

I reccomend we go with something that the majority are more comfortable with.

**Comment by jattanjie21** [comment]
Mern would be easier to maintain since most of the new developers are leaning toward the JS frameworks. But we can separate concerns and use the traditional stacks for backend and Js frameworks for the frontend. But i vote MERN.

**Comment by fanbondi** [comment]
Closing this as we have agreed to use Laravel!!
